# Тестовое задание NielsenIQ

In [37]:
### Мудрак Ирна Алексеевна

In [38]:
# В базе данных niq_test_db начинающий аналитик сохранил промо продажи одного SKU в разбивке по неделям.
# Схема public состоит из 3 таблиц:

![Схема таблиц](db.png)

#### Таблица sales

In [39]:
# store_id     - идентификатор магазина
# period_id    - порядковый номер периода
# sales_volume - продажи в рублях

# сэмпл данных:

#### Таблица store_chars

In [40]:
# store_id      - идентификатор магазина
# store_type_id - индентификатор типа магазина

# сэмпл данных

#### Таблица store_chars

In [41]:
# store_type_id - индентификатор типа магазина
# type_name - описание типа канала (мы будем работать только с супермаркетами)

# сэмпл данных

#### Промопериодом мы считаем непрерывный(!) отрезок времени, когда были продажи в рамках одного магазина:

![Пример](example.jfif)

### Задание:
#### Используя данные фактических продаж в канале супермаркетов необходимо найти:
 1. Общее количество промопериодов (во всех магазинах)
 2. Медиану продолжительности промопериода (количество недель)
 3. Объем  продаж по каждому промопериоду
 4. Медиану количества промопериодов на один магазин

**ВАЖНО: Задачу можно решить двумя способами — с использованием SQL или на Python. Мы приветствуем оба подхода, и если вы выполните оба варианта, это будет дополнительным преимуществом.** Такое решение позволит продемонстрировать ваши навыки работы как с базами данных и написания запросов, так и с инструментами аналитики и обработки данных на Python.

### Реализация

#### Импорт библиотек

In [42]:
#импорт библиотек
#!pip install psycopg2
from sqlalchemy import create_engine
from sqlalchemy import text
import pandas as pd

#### Импорт данных

In [43]:
def create_temp_engine():
    """
    Create connection
    """
    
    engine = create_engine('postgresql://niq_test_user:niq_test_pwd@rc1d-9nhcng0zw57wke57.mdb.yandexcloud.net:6432/niq_test_db')   
        
    return engine

#### Получение записей из public.sales

In [44]:
# пример запроса к базе
# request = """SELECT * FROM public.store_types LIMIT 10 """ 
request = """SELECT * FROM public.sales""" # получаем все записи из таблицы sales
engine = create_temp_engine()
with engine.connect() as con:
    sales_df = pd.read_sql(text(request), con)
engine.dispose()

sales_df.head(3)

   store_id  period_id  sales_volume  sale_id
0  42313622        226       1004.60        1
1  43346774        226        989.00        2
2  42312803        226        827.45        3

In [55]:
# # Можно было бы создать VIEW для периспользования, но permission denied for schema public
# create_period_groups_view = """
# CREATE OR REPLACE VIEW period_groups_view AS
# SELECT
#     s.store_id,
#     s.period_id,
#     s.period_id - ROW_NUMBER() OVER (PARTITION BY s.store_id ORDER BY s.period_id) AS promo_id
# FROM public.sales s
# """
#
# engine = create_temp_engine()
# with engine.connect() as con:
#     con.execute(text(create_period_groups_view))
#     con.commit()

### Функция для группировки периодов

In [56]:
def group_periods(sales_df):
    shop_periods = sales_df.sort_values(['store_id', 'period_id'])
    row_num = shop_periods.groupby('store_id').cumcount() # создаем правильные последовательности внутри групп по store_id
    promo_groups = shop_periods['period_id'] - row_num # вычисляем номера групп для промо периодов
    shop_periods['promo_id'] = promo_groups.groupby(shop_periods['store_id']).rank(method='dense').astype(int)

    return shop_periods.sort_values(['store_id', 'promo_id'])

#### 1. Общее количество промопериодов (во всех магазинах)

##### Решение на SQL

In [57]:
request = """
WITH shop_periods AS (
    -- делаем выборку из необходимых для работы столбцов
    SELECT
        s.store_id,
        s.period_id
    FROM public.sales s
),
period_groups AS (
    -- создаем критерий для группировки значения по номеру периода
    -- при увеличении на 1 разница между номером записи и номером периода сохраняется
    -- если разница между периодами не равна 1 - то меняется и номер группы
    -- таким образом получаем разные группы для разных последовательностей
    -- например
    -- 1 191 promo_id = 190
    -- 2 192 promo_id = 190
    -- 3 194 promo_id = 191

    -- чтобы promo_id шли с 1 можно создать CTE c использованием DENSE_RANK для promo_id
    -- вот так: DENSE_RANK() OVER (PARTITION BY store_id ORDER BY promo_id)
    -- но так, как в данном случаем нужено просто уникальное значение в рамках группы, в этом нет необходимости
    SELECT
        sp.store_id store_id,
        sp.period_id - ROW_NUMBER() OVER (PARTITION BY sp.store_id ORDER BY sp.period_id) AS promo_id
    FROM shop_periods sp
),
stores_promos_amounts AS (
    -- получаем количество промопериодов в каждом магазине
    -- не находим общую сумму для всех магазинов сразу, так как есть шанс совпадения номеров групп для разных магазинов
    SELECT
        COUNT(DISTINCT ps.promo_id) promos_count
    FROM period_groups ps GROUP BY ps.store_id
)
-- находим общее число промопериодов для всех магазинов
SELECT CAST(SUM(sa.promos_count) AS INTEGER) total_promos_amount FROM stores_promos_amounts sa
"""

engine = create_temp_engine()
with engine.connect() as con:
    df = pd.read_sql(text(request), con)
engine.dispose()

df.head(1)

   total_promos_amount
0               422976

##### Решение на python

In [58]:
def calculate_total_promos(sales_df):
    shop_periods = sales_df[['store_id', 'period_id']]
    shop_periods = group_periods(shop_periods)
    # считаем количество уникальных групп для каждого магазина
    stores_promos = shop_periods.groupby('store_id')['promo_id'].nunique().reset_index()
    stores_promos.columns = ['store_id', 'promos_count'] # переименовываем колонки
    # суммируем
    total_promos = stores_promos['promos_count'].sum().astype(int)

    return total_promos

# выводим результат
print(f"Total promo periods amount = {calculate_total_promos(sales_df)}")

Total promo periods amount = 422976

#### 2. Медиана продолжительности промопериода (количество недель)

##### Решение на SQL

In [59]:
request = """
WITH shop_periods AS (
    SELECT
        s.store_id,
        s.period_id
    FROM public.sales s
),
period_groups AS (
    SELECT
        -- группировка по промо периодам
        sp.store_id store_id,
        sp.period_id period_id,
        sp.period_id - ROW_NUMBER() OVER (ORDER BY sp.store_id, sp.period_id) AS grp
    FROM shop_periods sp
),
stores_promos_weeks_count AS (
    SELECT
        -- в каждом магазине для каждого промо периода считаем длительность в неделях
        ps.store_id store_id,
        COUNT (*) weeks_count
    FROM period_groups ps
    GROUP BY ps.store_id, ps.grp
)
    -- медиана для каждого магазина
    SELECT
        store_id,
        PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY weeks_count) promo_weeks_median
    FROM stores_promos_weeks_count
    GROUP BY store_id
    ORDER BY store_id

    -- общая медиана для всех промо периодов всех магазинв
    --SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY weeks_count) total_weeks_median FROM stores_promos_weeks_count
"""

engine = create_temp_engine()
with engine.connect() as con:
    df = pd.read_sql(text(request), con)
engine.dispose()

df.head(10)

   store_id  promo_weeks_median
0   4168621                 5.0
1   4168624                52.0
2   4168636                 2.5
3   4168639                 7.0
4   4168645                25.0
5   4168648                 7.0
6   4168651                 2.5
7   4168654                 2.0
8   4168660                 2.0
9   4168663                 3.0

##### Решение на python

In [60]:
def count_promos_duration_median(sales_df):
    shop_periods = sales_df[["store_id", "period_id"]]
    shop_periods = group_periods(shop_periods)

    # Группируем и считаем длительность каждой промо-акции
    promo_durations = (
        shop_periods.groupby(["store_id", "promo_id"])
        .size()
        .reset_index(name="weeks_count")
    )

    # Вычисляем медиану длительности для каждого магазина
    median_by_store = (
        promo_durations.groupby("store_id")["weeks_count"]
        .median()
        .astype(int)
        .reset_index(name="promo_weeks_median")
    )

    return median_by_store

stores_promo_duration_medians = count_promos_duration_median(sales_df)
stores_promo_duration_medians.head(10)

   store_id  promo_weeks_median
0   4168621                   5
1   4168624                  52
2   4168636                   2
3   4168639                   7
4   4168645                  25
5   4168648                   7
6   4168651                   2
7   4168654                   2
8   4168660                   2
9   4168663                   3

#### 3. Объем  продаж по каждому промопериоду

##### Решение на SQL

In [61]:
request = """
WITH shop_periods_sales AS (
    SELECT
        s.store_id,
        s.period_id,
        s.sales_volume
    FROM public.sales s
),
period_groups AS (
    SELECT
        -- группировка по промо периодам
        sp.store_id store_id,
        sp.sales_volume sales_volume,
        sp.period_id - ROW_NUMBER() OVER (ORDER BY sp.store_id, sp.period_id) AS grp
    FROM shop_periods_sales sp
)
    SELECT
        -- в каждом магазине для каждого промо периода считаем объем продаж
        ps.store_id store_id,
        DENSE_RANK() OVER (PARTITION BY ps.store_id ORDER BY ps.grp) AS promo_id,
        SUM(ps.sales_volume) AS promo_period_sales_volume
    FROM period_groups ps
    GROUP BY ps.store_id, ps.grp
"""

engine = create_temp_engine()
with engine.connect() as con:
    df = pd.read_sql(text(request), con)
engine.dispose()

df.head(10)

   store_id  promo_id  promo_period_sales_volume
0   4168621         1                  86.350000
1   4168621         2                   9.900000
2   4168621         3                  15.850000
3   4168621         4                  18.200000
4   4168621         5                  48.300003
5   4168621         6                  52.950000
6   4168624         1                1489.300200
7   4168636         1                   8.200000
8   4168636         2                  30.650000
9   4168636         3                  10.250000

##### Решение на python

In [62]:
def promo_sales_volume(sales_df):
    shop_periods = sales_df[["store_id", "period_id", "sales_volume"]]
    shop_periods = group_periods(shop_periods)

    sales_volume = (
        shop_periods.groupby(["store_id", "promo_id"])["sales_volume"].sum().reset_index(name="promo_period_sales_volume")
    )
    return sales_volume

stores_promo_sales_volume = promo_sales_volume(sales_df)
stores_promo_sales_volume.head(10)

   store_id  promo_id  promo_period_sales_volume
0   4168621         1                      86.35
1   4168621         2                       9.90
2   4168621         3                      15.85
3   4168621         4                      18.20
4   4168621         5                      48.30
5   4168621         6                      52.95
6   4168624         1                    1489.30
7   4168636         1                       8.20
8   4168636         2                      30.65
9   4168636         3                      10.25

#### 4. Медиану количества промопериодов на один магазин

##### Решение на SQL

In [63]:
request = """
WITH shop_periods AS (
    -- делаем выборку из необходимы для работы столбцов
    SELECT
        s.store_id,
        s.period_id
    FROM public.sales s
),
period_groups AS (
    SELECT
        sp.store_id store_id,
        sp.period_id - ROW_NUMBER() OVER (PARTITION BY sp.store_id ORDER BY sp.period_id) AS promo_id
    FROM shop_periods sp
),
stores_promos_amounts AS (
    -- получаем количество промопериодов в каждом магазине
    SELECT
        COUNT(DISTINCT ps.promo_id) promos_count
    FROM period_groups ps GROUP BY ps.store_id
)
SELECT PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY spa.promos_count) store_promos_amount_median FROM stores_promos_amounts spa
"""

engine = create_temp_engine()
with engine.connect() as con:
    df = pd.read_sql(text(request), con)
engine.dispose()

df.head(1)

   store_promos_amount_median
0                         6.0

##### Решение на python

In [64]:
def count_promos_amount_median_for_stores(sales_df):
    shop_periods = sales_df[["store_id", "period_id"]]
    shop_periods = group_periods(shop_periods)

    promos_amount = shop_periods.groupby(["store_id"])["promo_id"].nunique().reset_index(name="promos_amount_median")
    promo_median = (
        promos_amount["promos_amount_median"]
        .median()
        .astype(int)
    )
    return promo_median

stores_promo_amount_median = count_promos_amount_median_for_stores(sales_df)
print(f"stores_promos_amount_median = {stores_promo_amount_median}")

stores_promos_amount_median = 6



#### *Дополнительное задание

Дайте рекомендации начинающему аналитику как доработать текущую структуру базы данных
1.
2.